### ISSUE TITLE
Reboot module instead of shell and yum loop

### ISSUE THREAD

**Issue by anutator** [shu2003/ansible-linux-kernel-upgrade#1]
It's better to use reboot module (with or without additional options).
And use loop instead of with_items. Besides with yum it's better not to use loop and use it's own loop:

```
  - name: install kernel dev packages
    yum:
      name: 
      - ncurses-devel
      - bc
      - openssl-devel
      - hmaccalc
      - zlib-devel
      - binutils-devel
      - elfutils-libelf-devel
    state: present
```
